// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Athlete struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Performance *Performance `json:"performance,omitempty"`
}

type Performance struct {
	AvgSpeed   float64 `json:"avgSpeed"`
	InTraining bool    `json:"inTraining"`
}

type Query struct {
}
