package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"graphql-dataloader/graph/dataloader"
	"graphql-dataloader/graph/generated"
	"graphql-dataloader/graph/model"
)

// Performance is the resolver for the performance field.
func (r *athleteResolver) Performance(ctx context.Context, obj *model.Athlete) (*model.Performance, error) {
	return dataloader.GetPerformanceForOne(ctx, obj.ID)
}

// Athletes is the resolver for the athletes field.
func (r *queryResolver) Athletes(ctx context.Context) ([]*model.Athlete, error) {
	return r.athletesRepo.GetAthletes(ctx)
}

// Athlete returns generated.AthleteResolver implementation.
func (r *Resolver) Athlete() generated.AthleteResolver { return &athleteResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	athleteResolver struct{ *Resolver }
	queryResolver   struct{ *Resolver }
)
